rootProject.name="P2PChat"
include(
    ":app",
    ":app:binding",
    ":app:compose",
    ":core",
    ":core:data",
    ":core:feature",
    ":core:resource",
    ":libs",
    ":libs:p2p",
    ":libs:picture-selector"
)